name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check ip
        run: |
          ip addr

      - name: Install miredo
        run: |
          sudo apt install -y miredo
          sudo sed -i 's/ServerAddress	teredo-debian.remlab.net/ServerAddress teredo.iks-jena.de/g' /etc/miredo.conf
          sudo miredo
          cat /etc/miredo.conf
          sleep 1
          ip addr
          sleep 1
          ip addr
          sleep 1
          ip addr

      - name: Test IPv6
        run: |
          curl https://ipv6.icanhazip.com
          
